# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is 1 minute.

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "promtail"
    static_configs:
      - targets: ["promtail:9080"]

  - job_name: "ticket-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8121"]

  # 后续我们会在这里添加 Spring Boot Actuator 的监控端点
  # - job_name: "ticket-system-services"
  #   metrics_path: '/actuator/prometheus'
  #   static_configs:
  #     - targets: ["host.docker.internal:port"] # 示例
